=== Webern/pen/sourcecode/instrument-config/instrument-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="instrument-config" xmlns:inst="instrument-config">
  <xs:element name="kingdom" type="inst:kingdom-ct"> </xs:element>
  <xs:group name="main-group">
    <xs:sequence>
      <xs:element ref="inst:middle-c-octave"/>
      <xs:element ref="inst:middle-c-note-number"/>
      <xs:element maxOccurs="unbounded" ref="inst:kingdom"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="instrument-config">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="inst:main-group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:group name="classification-properties-group">
    <xs:sequence>
      <xs:element name="name"/>
      <xs:element name="id" type="inst:lookup-symbol-st"/>
    </xs:sequence>
  </xs:group>
  <xs:complexType name="kingdom-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element name="phylum" maxOccurs="unbounded" type="inst:phylum-ct"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="phylum-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element name="order" maxOccurs="unbounded" type="inst:order-ct"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="order-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element name="family" maxOccurs="unbounded" type="inst:family-ct"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="family-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element name="genus" maxOccurs="unbounded" type="inst:genus-ct"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="genus-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element name="species" maxOccurs="unbounded" type="inst:species-ct"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="species-ct">
    <xs:sequence>
      <xs:group ref="inst:classification-properties-group"/>
      <xs:element ref="inst:range"/>
      <xs:element ref="inst:transposition"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType final="" name="lookup-symbol-st">
    <xs:restriction base="xs:ID">
      <xs:pattern value="[a-z]{1}[a-z0-9]+([.]?[a-z0-9]+)*"/>
      <xs:minLength value="1"/>
      <xs:maxLength value="26"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="note-number-st">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="-256"/>
      <xs:maxInclusive value="256"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:group name="range-group">
    <xs:sequence>
      <xs:element name="lowest-note" type="inst:note-number-st"/>
      <xs:element name="highest-note" type="inst:note-number-st"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="range">
    <xs:complexType>
      <xs:group ref="inst:range-group"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="transposition-st">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="-72"/>
      <xs:maxInclusive value="72"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="transposition" type="inst:transposition-st"/>
  <xs:element name="middle-c-octave" type="inst:octave-number-st"/>
  <xs:simpleType name="octave-number-st">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="-3"/>
      <xs:maxInclusive value="12"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="middle-c-note-number" type="inst:note-number-st"/>
</xs:schema>

=== Webern/pen/sourcecode/instrument-config/instrument-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<instrument-config xmlns="instrument-config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fakeurl.com instrument-config.xsd">
  <middle-c-octave>4</middle-c-octave>
  <middle-c-note-number>72</middle-c-note-number>
  <kingdom>
    <name>Standard</name>
    <id>kingdom.standard</id>
    <phylum>
      <name>Strings</name>
      <id>phylum.strings</id>
      <order>
        <name>Bowed Strings</name>
        <id>order.bowed.strings</id>
        <family>
          <name>Orchestral Strings</name>
          <id>family.orchestral.strings</id>
          <genus>
            <name>Violins</name>
            <id>genus.violins</id>
            <species>
              <name>Violin</name>
              <id>species.violin</id>
              <range>
                <lowest-note>1</lowest-note>
                <highest-note>2</highest-note>
              </range>
              <transposition>0</transposition>
            </species>
          </genus>
        </family>
      </order>
    </phylum>
    <phylum>
      <name>Percussion</name>
      <id>phylum.percussion</id>
      <order>
        <name>Keyboard Percussion</name>
        <id>order.keyboard.percussion</id>
        <family>
          <name>Wooden Keyboards</name>
          <id>family.wooden.keyboards</id>
          <genus>
            <name>Marimbas</name>
            <id>genus.marimbas</id>
            <species>
              <name>Marimba 4.3</name>
              <id>species.marimba.4.3</id>
              <range>
                <lowest-note>1</lowest-note>
                <highest-note>2</highest-note>
              </range>
              <transposition>0</transposition>
            </species>
          </genus>
        </family>
      </order>
    </phylum>
  </kingdom>
</instrument-config>
